//
// Generated by JTB 1.3.2
//

package ansem.syntaxtree;

import gci.tree.IRType;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;VIRGULA&gt;
 * f1 -> Type()
 * f2 -> &lt;ID&gt;
 * </PRE>
 */
public class FormalRest implements Node {
   public NodeToken f0;
   public Type f1;
   public NodeToken f2;

   public FormalRest(NodeToken n0, Type n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FormalRest(Type n0, NodeToken n1) {
      f0 = new NodeToken(",");
      f1 = n0;
      f2 = n1;
   }

   public IRType accept(ansem.visitor.IRVisitor v) throws SemanticException {
      return v.visit(this);
   }

   public void accept(ansem.visitor.Visitor v) throws SemanticException {
      v.visit(this);
   }
   public <R,A> R accept(ansem.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ansem.visitor.GJNoArguVisitor<R> v)  throws SemanticException {
      return v.visit(this);
   }
   public <A> void accept(ansem.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

