//
// Generated by JTB 1.3.2
//

package ansem.syntaxtree;

import gci.tree.IRType;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;INT&gt; &lt;LCOL&gt; &lt;RCOL&gt;
 *       | &lt;INT&gt;
 *       | &lt;BOOLEAN&gt;
 *       | &lt;ID&gt;
 * </PRE>
 */
public class Type implements Node {
   public NodeChoice f0;

   public Type(NodeChoice n0) {
      f0 = n0;
   }

   public IRType accept(ansem.visitor.IRVisitor v) throws SemanticException {
      return v.visit(this);
   }
   
   public void accept(ansem.visitor.Visitor v) throws SemanticException {
      v.visit(this);
   }
   public <R,A> R accept(ansem.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ansem.visitor.GJNoArguVisitor<R> v)  throws SemanticException {
      return v.visit(this);
   }
   public <A> void accept(ansem.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

